CI: Disable clang-3.5 std=14,17 jobs
Clang 3.5 std=14,17 builds are broken now (due to changes in dependencies?):

```
error: debug information for auto is not yet supported
```